apiVersion: milvus.io/v1beta1
kind: Milvus
metadata: 
    name: unibot-vector-db
    labels:
        app: milvus
    namespace: milvus-db
spec: 
    mode: cluster
    dependencies: {}
    components: 
        queryNode:
            replicas: 2
            resources: 
                limits: 
                    cpu: "4"
                    memory: 8Gi
                requests:
                    cpu: "2"
                    memory: 4Gi 
        datanode: 
            replicas: 2
                nodeSelector: 
                storage-type: 
                     
    config: {}
