services:
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unibot-v2-orchestrator
    network_mode: "host"
    volumes: 
      - ./mcp_servers.json:/app/config/mcp_servers.json
    environment:
      # Match the environment variables to your custom stack initialization defaults
      - MODEL_ENDPOINT_BASE_URL=http://192.168.1.207:11434/v1
      - MODEL_NAME=gemma4:12b

    # Restarts the container if a connection drops temporarily during boot sequences
    restart: on-failure
  prometheus:
    image: prom/prometheus
    network_mode: "host"
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"
