# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with ramalama-0.13.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ramalama
  labels:
    app: ramalama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ramalama
  template:
    metadata:
      labels:
        app: ramalama
    spec:
      containers:
        - name: ramalama
          image: rlcr.io/ramalama/gemma-3-4b-it:llamacpp-cuda 
          resources:
            limits:
              nvidia.com/gpu: 1
          ports:
            - containerPort: 8080
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: CUDA_VISIBLE_DEVICES
              value: all
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
---
apiVersion: v1
kind: Service
metadata:
    name: ramalama-svc
spec:
    selector:
        app: ramalama
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
    type: LoadBalancer

