apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: internal-proxy-config
  namespace: envoy-gateway-operator
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: ClusterIP  
