apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-operator
  namespace: argocd
spec:
  project: unibot-v2
  source:
    repoURL: docker.io/envoyproxy
    chart: gateway-helm
    targetRevision: 1.7.0
    helm:
      values: |
        skipCrds: false
        deployment:
          envoyGateway:
            replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
