apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: streamlit-ui-route
  namespace: streamlit-ui
spec:
  parentRefs:
  - name: streamlit-ui-gateway
    namespace: streamlit-ui 
    sectionName: http
  rules:
  - matches:
    - path: 
        type: PathPrefix
        value: /
    backendRefs:
    - name: streamlit-ui-svc
      port: 8001
    sessionPersistence:
      sessionName: UNIBOT-UI-SESSIONS
      type: Cookie
      cookieConfig:
        lifetimeType: Session

