apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openwebui-route
  namespace: openwebui
spec:
  parentRefs:
  - name: openwebui-gateway
    namespace: openwebui
    sectionName: http 
  rules:

  # For front-end
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: openwebui-open-webui
      port: 80
    sessionPersistence:
      sessionName: OPEN_WEBUI_SESSIONS
      type: Cookie
      cookieConfig:
        lifetimeType: Session

  # For stateless API requests that require longer timeouts
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: openwebui-open-webui
      port: 80
