apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gcp-2
  region: us-east-1
  version: "1.34"
nodeGroups:
  - name: ramalama-gpu-workers
    instanceType: g6.xlarge
    ami: ami-096d79104714a752d
    amiFamily: Ubuntu2204
    minSize: 1
    desiredCapacity: 1
    maxSize: 1
    volumeSize: 100
    overrideBootstrapCommand: |
      #! /bin/bash
      source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh
      /etc/eks/bootstrap.sh ${CLUSTER_NAME} --container-runtime containerd --kubelet-extra-args "--node-labels=${NODE_LABELS}"
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      roleName: gcp-ebs-csi-controller-sa
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy 
    - metadata:
        name: my-service-account
        namespace: default
      attachPolicyARNs:
        - arn:aws:iam::620339869704:policy/gcp-oidc-managed-policy
      roleName: gcp-oidc-role

addons:
    - name: aws-ebs-csi-driver 

accessConfig:
  accessEntries:
    - principalARN: arn:aws:iam::620339869704:user/nick_bottari@student.uml.edu
      accessPolicies:
        - policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
          accessScope:
            type: cluster
    - principalARN: arn:aws:iam::620339869704:user/gurpreet_singh@student.uml.edu
      accessPolicies:
        - policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
          accessScope:
            type: cluster
    - principalARN: arn:aws:iam::620339869704:user/roshankarthik_rajesh@student.uml.edu
      accessPolicies:
        - policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
          accessScope:
            type: cluster
    - principalARN: arn:aws:iam::620339869704:user/nicolas_busse@student.uml.edu
      accessPolicies:
        - policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
          accessScope:
            type: cluster
