apiVersion: v1
kind: Service
metadata:
  name: webui-svc
spec:
  selector:
    app: openwebui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 443
      targetPort: 8080
      name: https
  type: LoadBalancer
