apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-database
spec:
  template:
    spec:
      containers:
      - name: rag-database
        image: 620339869704.dkr.ecr.us-east-1.amazonaws.com/gcp_ecr_repository:latest
        ports:
        - containerPort: 6333
# This will need a configured service account to pull from ECR
# ADD THAT IN
