apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: unibot-stack
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://github.com/UMLCloudComputing/unibot-v2.git
        targetRevision: HEAD
        target: main
        path: argocd/apps 
    directory:
        recurse: true
    destination: 
        name: https://kubernetes.default.svc
        namespace: argocd
    syncPolicy:
        syncOptions:
            - CreateNamespace=true
        automated:
            prune: true
            selfHeal: true

