apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-mcp-scraper
  namespace: mcp  
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-mcp-scraper-binding
  namespace: mcp  # Must match the Role namespace
subjects:
- kind: ServiceAccount
  name: mcp-sa
  namespace: monitoring 
roleRef:
  kind: Role
  name: prometheus-mcp-scraper
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-sa
  namespace: monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: unibot-prometheus-mcp
  namespace: monitoring
  labels:
    prometheus: unibot-prometheus-mcp
spec:
  replicas: 2
  serviceAccountName: mcp-sa

  serviceMonitorSelector:
    matchLabels:
      app: mcp 

  podMonitorSelector:
    matchLabels:
      app: mcp

  serviceMonitorNamespaceSelector:
    matchNames:
      - mcp

  retention: 10d
  resources:
    requests:
      memory: 400Mi
    limits:
      memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-mcp-svc
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9090
      targetPort: 9090
  selector:
    prometheus: unibot-prometheus-mcp
