apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-stack
  annotations:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: unibot-v2
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 86.3.2
    helm:
      values: |
        grafana: 
          enabled: true
        alertManager:
          enabled: true
        nodeExporter:
          enabled: false
        prometheus:
          enabled: false # Disable default global prometheus in favor for seperate one in monitoring namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus-stack
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
