apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: unibot-infra
    namespace: argocd
    annotations:
        argocd.argoproj.io/sync-wave: "-10"
spec:
    project: default
    source:
        repoURL: https://github.com/UMLCloudComputing/unibot-v2.git
        targetRevision: HEAD
        path: argocd/apps/infrastructure
    destination:
        name: admin@unibot-cluster
        namespace: argocd
    syncPolicy:
        syncOptions:
            - CreateNamespace=true
        automated:
            prune: true
            selfHeal: true
            allowEmpty: true 
