apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/hook: PreSync
  finalizers:
    - resources-finalizers.argocd.argoproj.io 
spec:
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.5.x
    helm:
      values: |
        persistence:
          defaultClass: true
        defaultSettings:
            defaultDataPath: /var/lib/longhorn
            storageReservedPercentageForDefaultDataPath: 15
    project: default
  destination:
    name: admin@unibot-cluster
    namespace: longhorn-system 
  syncPolicy:
    syncOptions:
        - CreateNamespace=true
    automated:
        prune: true
        selfHeal: true
    managedNameSpaceMetadata:
        labels:
            pod-security.kubernetes.io/enfore: privileged
