# Required Secrets:
# webui-secret-key    -> Configure yourself, IE openssl rand -hex 32
# postgresql-db-url   -> Configured with login credentials from postgresql namespace secret
# redis-url           -> Configure with global password from redis namespace secret
# pipelines-api-key   -> (OPTIONAL) If using Open WebUI pipelines (as microservice). Configure yourself, IE openssl rand -hex 32

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openwebui
  namespace: argocd
spec:
  project: unibot-v2
  source: 
    repoURL: https://open-webui.github.io/helm-charts
    targetRevision: 12.11.0
    chart: open-webui
    helm:
      values: |
        replicaCount: 5
        websocket:
          redis:
            enabled: false
        ollama:
          enabled: false
        tika:
          enabled: false
        pipelines:
          enabled: false
          extraEnvVars:
            - name: PIPELINES_API_KEY
              valueFrom:
                secretKeyRef:
                  name: pipelines-api-key
                  key: key
            - name: GLOBAL_LOG_LEVEL
              value: DEBUG
        extraEnvVars:
          - name: OPENAI_API_BASE_URL
            value: "http://openwebui-pipelines.openwebui.svc.cluster.local:9099"
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: pipelines-api-key
                key: key
          - name: WEBUI_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: webui-secret-key
                key: key
          - name: ENABLE_DB_MIGRATIONS
            value: "false"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgresql-db-url
                key: url
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: redis-url
                key: url
          - name: WEBSOCKET_MANAGER
            value: "redis"
          - name: ENABLE_WEBSOCKET_SUPPORT
            value: "true"
          - name: WEBSOCKET_REDIS_URL
            valueFrom:
              secretKeyRef:
                name: redis-url
                key: url
        persistence:
          provider: local
          accessModes:
            - ReadWriteMany
          storageClass: 'longhorn'
  destination:
    server: https://kubernetes.default.svc
    namespace: openwebui
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true


