apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: unibot-operators
    namespace: argocd
    annotations:
        argocd.argoproj.io/sync-wave: "0"
spec:
    project: unibot-v2
    source:
        repoURL: https://github.com/UMLCloudComputing/unibot-v2.git
        targetRevision: HEAD
        path: argocd/apps/operators
    destination:
        server: https://kubernetes.default.svc
        namespace: argocd
    syncPolicy:
        syncOptions:
            - CreateNamespace=true
        automated: 
            prune: true
            selfHeal: true
            allowEmpty: true 
