apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificates-tls-secret
  namespace: redis
spec:
  secretName: certificates-tls-secret
  duration: 2160h  # 90 days
  renewBefore: 360h  # 15 days
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
  commonName: redis-master.redis.svc.cluster.local
  dnsNames:
  - redis-master
  - redis-master.redis
  - redis-master.redis.svc.cluster.local
  - redis-replicas
  - "*.redis-replicas.redis.svc.cluster.local"
