# Required secrets:
# postgres-secret:
#   postgres-password    -> DB admin password
#   password             -> DB user password (used by applicaiton)
#   replication-password -> Password for replication user to replicate data from DB

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: postgresql
    namespace: argocd
    annotations: 
        argocd.argoproj.io/sync-wave: "10"
spec:
    project: unibot-v2
    source:
        chart: postgresql
        repoURL: https://charts.bitnami.com/bitnami 
        targetRevision: 15.x.x
        helm:
            values: |
                  auth:
                    database: "unibot_db"
                    username: "unibot_user"
                    existingSecret: "postgres-secret" 
                    secretKeys:
                      adminPasswordKey: 'postgres-password'
                      userPasswordKey: 'password'
                      replicationPasswordKey: 'replication-password'
                  primary:
                    persistence:
                      enabled: true
                      size: 80Gi
                      storageClass: longhorn
                    mountPath: /bitnami/postgresql
                    resources:
                      limits:
                        cpu: "1"
                        memory: "2Gi"
                  image: 
                    tag: latest 
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: postgresql
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
