apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io 
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.13.0 # Lock this to a specific version for stability
    helm:
      values: |
        installCRDs: true
        replicaCount: 2
        resources:
            requests:
                cpu: 10m
                memory: 32Mi
      parameters:
        - name: installCRDs
          value: "true" # Critical: Cert-Manager needs its CRDs to function
  destination:
    name: admin@unibot-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
