apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.5.x
    helm:
      values: |
        persistence:
          defaultClass: true
        defaultSettings:
            defaultDataPath: /var/lib/longhorn
            storageReservedPercentageForDefaultDataPath: 15
        preUpgradeChecker:
            jobEnabled: false   # This conflicts with ArgoCD. Chicken/Egg problem.
  destination:
    name: admin@unibot-cluster
    namespace: longhorn 
  syncPolicy:
    syncOptions:
        - CreateNamespace=true
    automated:
        prune: true
        selfHeal: true
    managedNameSpaceMetadata:
        labels:
            pod-security.kubernetes.io/enfore: privileged
