apiVersion: v1
kind: Namespace
metadata:
  name: 
  labels:
    app: discord-bot
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-config
  labels:
    app: discord-bot
data:
  REDIS_URL: http://redis-headless.redis.svc.cluster.local
  ORCHESTRATOR_URL: http://api-orchestrator-svc.api-orchestrator.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  labels:
    app: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
      - name: bot
        image:
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: bot-secrets # Not provided in this manifest, must be set manually into the namespace
              key: discord-token 
        envFrom:
        - configMapRef:
            name: bot-config
