on:
    schedule:
        - cron: '0 1 1 * *' # Runs at 1:00 AM on the first day of every month

jobs:
    deep-update-rag-db:
        runs-on: arc-runner-set
        steps:
            - uses: actions/checkout@v4
            
            - name: Install dependencies
              run:  pip install asyncio aiohttp ollama 

            - name: Download Data
              run: python3 rag-scripts/parallel_download.py --file links.txt
              
            - name: Refresh Milvus DB
              run: python3 rag-scripts/refresh-data.py --path html_data

