name: Refresh DB with ETL Pipeline
on:
    workflow_dispatch:

    push: 
        branches: [ main ]
        paths: [ 'links.txt' ]

# Avoid state locks
concurrency:
 group: db-etl-pipeline
 cancel-in-progress: false
    
jobs:
    db-etl-pipeline:
        runs-on: unibot-runner-set # Specific to ARC installation on production cluster
        env:
            OLLAMA_BASE_URL: ${{ vars.OLLAMA_BASE_URL }}
            DOCLING_BASE_URL: ${{ vars.DOCLING_BASE_URL }}
            MILVUS_HOST: ${{ vars.MILVUS_HOST }}
            MILVUS_PORT: ${{ vars.MILVUS_PORT }} 
            COLLECTION_NAME: ${{ vars.COLLECTION_NAME }}
            LOG_OUTPUT_PATH: ${{ vars.LOG_OUTPUT_PATH }}
            URL_LIST_FILE: "../links.txt"
            OP_FILES_PATH: ${{ vars.OP_FILES_PATH }}
         
        defaults:
            run:
                working-directory: ./rag-scripts/
        
        steps:
          - name: Checkout Code
            uses: actions/checkout@v6

          - name: Install uv 
            uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
            with:
              enable-cache: true

          - name: Setup Python
            uses: actions/setup-python@v5
            with:
                python-version: '3.14'
            
          - name: Install ETL Project
            run: uv sync --locked --all-extras 
            
          - name: Synchronize Changes
            run: |
                uv run src/mt_rag_sync_manager.py
            
          - name: Handle Deleted URLs
            run: |
                uv run src/delete_data.py
            
          - name: Handle New URLs
            run: |
                uv run src/add_data_t.py
          
          - name: Export Logs for Analysis
            if: always()
            uses: actions/upload-artifact@v4
            with:
                name: run-logs-${{ github.run_id }}
                path: /home/runner/data/logs/ 
                retention-days: 1 # Keep storage clean by deleting after 24 hours
