on:
    push:
        paths:
            - links.txt

jobs:
    shallow-update-rag-db:
        runs-on: arc-runner-set
        steps: 
            - uses: actions/checkout@v4
              
            - name: Process links 
              id: get_links
              run: | 
                # Get new links and save to file
                git diff -U) HEAD^ HEAD links.txt | grep '^\+' | grep -v '^\+\+\+' | sed 's/^\+//' > new_links.txt
               
                # Get deleted links 
                git diff -U0 HEAD^ HEAD links.txt | grep '^-' | grep -v '^---' | sed 's/^-//' > deleted_links.txt

            - name: Process Removals 
              run: python3 rag-scripts/remove_data.py --file deleted_links.txt
    
            - name: Download new files
              run: python3 rag-scripts/parallel_download.py --source_file new_links.txt
 
            - name: Process Additions
              run: python3 rag-scripts/add_data.py --file new_links.txt 

